import { ImageType } from "../../types/image-type"

export const newZealandPictures: ImageType[] = [ 
{ img_id: '1fxwpVpyCaJNc_s7vpwfXqtthZQO--TLs',
description: 'Hamilton Gardens' },
{ img_id: '1fz6iF2SXU3zy2Jfqq9ZP9KQltUNdPcMy',
description: 'Hamilton Gardens' },
{ img_id: '1g6U16ZvqINob4V9N2Mnw9jMrnAhpoXmg',
description: 'Hamilton Gardens' },
{ img_id: '1gCBdr-w6huoqgnAxbm73wAY8V8I93RE-',
description: 'Hamilton Gardens' },
{ img_id: '1gDgL-BSd3Zy3ju8bzksisluphNgwUvwk',
description: 'Hamilton Gardens' },
{ img_id: '1gLytxj-MPHpYX0PwsD-s6Rew1PJBZeR9',
description: 'Hamilton Gardens' },
{ img_id: '1gNW73Zk1YvTBzKGBkKG4VmJlK5NcFni4',
description: 'Hamilton Gardens' },
{ img_id: '1gNvEbkiuyiMumPTEb2IRPkWn4hh-Rpgd',
description: 'Hamilton Gardens' },
{ img_id: '1gcLSR3HlAcl-iMRtQn6EfINTTJpmTKy9',
description: 'Hamilton Gardens' },
{ img_id: '1gfdcl-XY1W23sDXQne_OHBgT32-bwaTZ',
description: 'Hamilton Gardens' },
{ img_id: '1giQasHazGiex54lIZbV8cs0MKEOs8lzw',
description: 'Hamilton Gardens' },
{ img_id: '1gnV04FXSXcVmNUIMsTEKoXAOb8JaHkpx',
description: 'Hamilton Gardens' },
{ img_id: '1gpdyCi0CCm-05G-R_pA3eG8DJddvN3Qz',
description: 'Hamilton Gardens' },
{ img_id: '1gptVjqM3ou1fxEaJYKN5V_T51W2vMRdB',
description: 'Hamilton Gardens' },
{ img_id: '1h8kIkYZwq4XbiQ63ZVOQGCMy3TPCI2s-',
description: 'Hamilton Gardens' },
{ img_id: '1hBNWIHgySyAi8gcyTROZ_y6-wQWucAVH',
description: 'Hamilton Gardens' },
{ img_id: '1hBwoUDn25Noi8e49Yl9Y3w3eWlbuPCg8',
description: 'Hamilton Gardens' },
{ img_id: '1hFY3IYJdNvVMHN10aLtAYx73Jl7J40bj',
description: 'Hamilton Gardens' },
{ img_id: '1hNmJMzBz6IPR6NtqTfiYtuXJGXeJM9yA',
description: 'Hamilton Gardens' },
{ img_id: '1hTgx8woLAJgiJHVEX8_38SuQt2CxC0Kz',
description: 'Hamilton Gardens' },
{ img_id: '1hUD2y2UUsg58w6dOA9wbTwhD3k3yBx3i',
description: 'Hamilton Gardens' },
{ img_id: '1h_UfM8u44Hxo_Dmm4lTLe_20x02o6rlu',
description: 'Hamilton Gardens' },
{ img_id: '1h_lSCnJrMTITGFiAcJTKbBJE1OiwfeWh',
description: 'Hamilton Gardens' },
{ img_id: '1hdGOgFGKRy-JLA_ZUDiWaoPyC5ykzAq5',
description: 'Hamilton Gardens' },
{ img_id: '1hgNJKKGWHK5ap_ZIeGWOqskA_Kq-J7Mt',
description: 'Hamilton Gardens' },
{ img_id: '1hiRSC_Mg09ff2EjrvBfVmNDt2KoEzahY',
description: 'Hamilton Gardens' },
{ img_id: '1hpxUgoGXnmlDTUNnWGIg1UsLIXcpJhiC',
description: 'Hamilton Gardens' },
{ img_id: '1hr8zfPBkB7K46CQ4uUhGwrZUxq8Zhwsc',
description: 'Hamilton Gardens' },
{ img_id: '1hrXZE80zmWTi_lfjz_jA5bddE8b7Z-MU',
description: 'Hamilton Gardens' },
{ img_id: '1iDYcNfewJC-b5St6EtPuCSZdMWaphadY',
description: 'Hamilton Gardens' },
{ img_id: '1iQnAn5IUiGTR3vokS4TM9kCcgZNf5SNh',
description: 'Hamilton Gardens' },
{ img_id: '1i_tnp5NReraWvj9iMDopVfte4sBA3Z21',
description: 'Hamilton Gardens' },
{ img_id: '1ifbAjHq1DGW2d0_1Nsm7lWFy4Qwi9kE2',
description: 'Hamilton Gardens' },
{ img_id: '1ig1s0pLaoKaLKjyK8fd8F-HaoalQS3vl',
description: 'Hamilton Gardens' },
{ img_id: '1eqBOW11XotlRTBAHvIOyYAQJ66Vfk0lq',
description: 'Auckland' },
{ img_id: '1ek_l9oqiJfonYj9hkQTRhGmHDBpToSQw',
description: 'Auckland' },
{ img_id: '1egsI0ZbS5yi_thKUlJ6C4PoMWc9xz7tH',
description: 'Auckland' },
{ img_id: '1eecuZzjgjJ9uxHBAUsz_P8mHWdPYvW5x',
description: 'Auckland' },
{ img_id: '1edpVtcXNfDlJq3U8hNDvaJfh9Za3ohKr',
description: 'Auckland' },
{ img_id: '1eUfr1pmA54x6yZyMfMBLIjlmBCGhxJbA',
description: 'Auckland' },
{ img_id: '1eTin0zDWu8iFM4qbAlgGwD7MqPBZ1DQf',
description: 'Auckland' },
{ img_id: '1ePkoG8RhFw2eRSurWIhHSQ6LMxpVC-H5',
description: 'Auckland' },
{ img_id: '1ePLxKaHoj2LbmDsjTP89YDmxiN0slJVy',
description: 'Auckland' },
{ img_id: '1eCz6HybaqwKd52uvD3APsv0cXNy7K2kb',
description: 'Auckland' },
{ img_id: '1e8DliLRbUdtYXEfLDkx5GQKqLXkeIDe7',
description: 'Auckland' },
{ img_id: '1e5vVy0SoBXTp-00_e6pOXZ9_BTZfG82G',
description: 'Auckland' },
{ img_id: '1e4xtOIg1GliiMGWK4LHIdMQCbcRqXiON',
description: 'Auckland' },
{ img_id: '1dxdaJ4ozrxDK6znGrGZ0M-lf130N7zqe',
description: 'Auckland' },
{ img_id: '1dtspFr80FGx0ZJGvIZKucTOZ8oS5bOHM',
description: 'Auckland' },
{ img_id: '1drICDgCAQ0ptsLQFKSLVDl3a5oQHOpyc',
description: 'Auckland' },
{ img_id: '1dpagW3MqBiGTjwtgdxpjpxSrhskA9iAX',
description: 'Auckland' },
{ img_id: '1dadScYWgsZ_11tYJIfnejuDNi89DZgnR',
description: 'Auckland' },
{ img_id: '1dW1ziRRAvtPzV_DZ3CXjYhoffqVb-Dtb',
description: 'Auckland' },
{ img_id: '1dU8Udtx_8uVc5EnlM5G3Id_Syrt5Rs6_',
description: 'Auckland' },
{ img_id: '1dRk4eNuuAvvZbDYqysjabqyG5ciZxNH5',
description: 'Auckland' },
{ img_id: '1dH5K1xvk5W5hlxl4SWsiP277s2G0WLr2',
description: 'Auckland' }]
