import { ImageType } from "../../types/image-type";

export const washingtonImages: ImageType[] = [ 
  { img_id: '1TSdrxHxfle5oczZNf2-QBfBo8RwdR6_-',
  description: 'Seattle; Public Markey Center' },
{ img_id: '1TULZ2FhYMS-o4THEnxgfrX2epm7IZYBG',
  description: 'Seattle; Cityscape' },
{ img_id: '1TVsU3lPhmK0qdb3Vy2UrPXR7p9y97xX1',
  description: 'Seattle; Cityscape' },
{ img_id: '1TaUG36oxjT4fP7TV-0lbsCvmG9bYySot',
  description: 'Seattle; Cityscape' },
{ img_id: '1TcO7WIkPtSfuK-rEG9eKivgeE8XPyx7G',
  description: 'Seattle; Bainbridge Ferry' },
{ img_id: '1TcWV05VXyHlrvCgPiW9763cwuabIHLOP',
  description: 'Seattle; Bainbridge Ferry' },
{ img_id: '1TnJW4YUybu8LZxpd0HPXpueEH2e97bDD',
  description: 'Seattle; Bainbridge Island' },
{ img_id: '1U6iXMCGKhVsCxUoQi8b_Xu8jFRLy9m9p',
  description: 'Seattle; Bainbridge Island' },
{ img_id: '1U7_sHGUgBKoHB8AT6bhJte0aOJ4Z4W1O',
  description: 'Seattle; REI Store Landscape' },
{ img_id: '1U882TsC7ojlGaf7osnqT69bN3QcA279-',
  description: 'Seattle; Space Needle' },
{ img_id: '1U8Q_RkIu8mMokLr7SEtN2QDJM5TMjlIu',
  description: 'Seattle; Space Needle' },
{ img_id: '1UBA4YlQoIgQCKTGxoa6NGfNZPLBKqqiz',
  description: 'Seattle; Cityscape - Amazon Balls' },
{ img_id: '1UIWdJimbV0n_AOR6p-fZAPfTnx_WKdNt',
  description: 'Seattle; Cityscape' },
{ img_id: '1UJiDsJE3KinXSPDN0VcDVePrCXG5lbzQ',
  description: 'Port Angeles; Driving - Ocean' },
{ img_id: '1UPKN_m87DVodDi_BSkS_HDtBJX0noW2d',
  description: 'Port Angeles; Driving - Misty Mountains' },
{ img_id: '1UPUUOqNncwKSrwaMnK9cPeeQ-gWDoBVx',
  description: 'Port Angeles; Hiking' },
{ img_id: '1UQwoCpErCYUbZ5Fk2Kgs8y2iUm_1lbk4',
  description: 'Random; Slug' },
{ img_id: '1UUgW35Zch7EkK1mjs8v-athj6wGRaljd',
  description: 'Random; Snail' },
{ img_id: '1UWODi1yKvG5lEeH3Wi3-tu7oDbnUhvzU',
  description: 'Random; Snail' },
{ img_id: '1UXPPCZYugA462snAx6d_UAgecZYOY6DY',
  description: 'Port Angeles; Hiking' },
{ img_id: '1UlUrjvt5bWZiw2rO2W8assdTsTB9N85W',
  description: 'Port Angeles; Hiking' },
{ img_id: '1Urmt_7vUKOYxjwpX3SM4mjCSY27F3CEX',
  description: 'Port Angeles; Devil\'s Punchbowl' },
{ img_id: '1UsmPbbH-ecyrvWiidgwflKVdCHkHivSm',
  description: 'Port Angeles; Devil\'s Punchbowl' },
{ img_id: '1UtC5g4vTgGznBpPxZ7J2PLeymMulKqZN',
  description: 'Port Angeles; Devil\'s Punchbowl' },
{ img_id: '1Uv9hS92h_4JZF9cJMum5GFS7YerWtyqz',
  description: 'Port Angeles; Devil\'s Punchbowl' },
{ img_id: '1VH11UaMn6hoCQhz2C0ZD0Lh3dC2AWoqY',
  description: 'Port Angeles; Devil\'s Punchbowl' },
{ img_id: '1VPLKWo3Se487uDx-2yqqCl0UCyxdw_9g',
  description: 'Port Angeles; Devil\'s Punchbowl' },
{ img_id: '1VQpqAO4dMgiIEEeIq6nBPeTnkq44tQ2E',
  description: 'Port Angeles; Devil\'s Punchbowl Hike' },
{ img_id: '1VSClv8izo4NQUCkJ8XivY7EklgHBw6aS',
  description: 'Port Angeles; Hiking - Giant Tree' },
{ img_id: '1VYJ7fyQxAdI-hqYDjsHsJXa-TVlbnCy1',
  description: 'Random; Hoh Rain Forest' },
{ img_id: '1VY_RmQ_1KzxMdmJ0QmC1VCxgC3J62HHf',
  description: 'Random; Hoh Rain Forest' },
{ img_id: '1VffBHYBsKcTWjuNf3XWvQ-QqbIkNrXDc',
  description: 'Random; Hoh Rain Forest' },
{ img_id: '1VdYKI0o_wH0-8oqb2sgLLMAW4UqsZy9p',
  description: 'Random; Hiking - Giant Fallen Tree (Katelyn for size)' },
{ img_id: '1VimJRjNAE_2CgzL-X5mpuMdr6Fx8VIDE',
  description: 'Random; Hiking' },
{ img_id: '1Vj8qR5Oyr6dLMhGR2bHRKYHA3DzrJYqA',
  description: 'Random; Hiking' },
{ img_id: '1Vl3zKCRi7VeJfjuowx0oivzsR2rV4DBa',
  description: 'Port Angeles; Hiking' },
{ img_id: '1VmyxBp1Vm_b1A4Kf51OFjdLGWqYoN8BH',
  description: 'Cape Flattery; Wack Fish Gal' },
{ img_id: '1W1c6_xZoGuvjiX6P-JNY55G9xbq4Xwo1',
  description: 'Cape Flattery; Ocean Time' },
{ img_id: '1VzC254OTUMtsfe4ZK3yjx2pzIPjdS6LV',
  description: 'Cape Flattery; Ocean Time' },
{ img_id: '1W45duA2dBe3CePkL8jFqQaB4vYxu7rtq',
  description: 'Cape Flattery; Ocean Time' },
{ img_id: '1W9UBVrjaws_3hEvDEpPc_6kj5QEnuygn',
  description: 'Cape Flattery; Ocean Time' },
{ img_id: '1WGE5187j2IU4zxe5qJ5MaGl_4fSHEXi0',
  description: 'Cape Flattery; Ocean Time with Sick Tree' },
{ img_id: '1WRAvrY_NQDv83x8ayUWjYyfRJKLwQyLe',
  description: 'Cape Flattery; Ocean Time' },
{ img_id: '1WSgu6PH9DrMLGXuo9WA2Bx9wP_RKzweD',
  description: 'Cape Flattery; Ocean Time' },
{ img_id: '1WTbePmQJozQwLLd19PNwzNQ6urdwcG5H',
  description: 'Cape Flattery; Ocean Time' },
{ img_id: '1WTjUQ909FYbZ5_NNVksiLez0q35shRnq',
  description: 'Cape Flattery; Ocean Time' },
{ img_id: '1YVi1A7QvYRw8BvYSeQ4u9oI6FNP-5b0V',
  description: 'Cape Flattery; Ocean Time' },
{ img_id: '1W_cPN0nt3FDaSJirnI53Y6BiELQK7l_z',
  description: 'Cape Flattery; Ocean Time' },
{ img_id: '1YV0HUIF4RZ_9iCztRTQ0pcCPsgkMZSFQ',
  description: 'Random; Forks - Bella\'s Truck' },
{ img_id: '1WdHYa7pO_ZPEfL6a3eB-gubYUlKzl1-D',
  description: 'Port Angeles; Mount Storm King' },
{ img_id: '1WefxOYIueOsvjehfoFjlcEO8XDIyXfE1',
  description: 'Port Angeles; Madison Falls' },
{ img_id: '1Wfs0ZW0S-s67d2l6pTfb-pNfRIQQ0FDF',
  description: 'Port Angeles; Mount Storm King' },
{ img_id: '1WysEOq9LCQfT4OSTpYXe7Th2J5SUHzt4',
  description: 'Port Angeles; Mount Storm King' },
{ img_id: '1Wz_4LzZoY0QdHiehglfgXQfZ7hC7AyLP',
  description: 'Port Angeles; Mount Storm King' },
{ img_id: '1YHvsbGRyGX3nwpzn86Xz4RzivRfgqCUL',
  description: 'Port Angeles; Mount Storm King' },
{ img_id: '1YQRcJEYZGqaNhUt_BfmHo-3-M3FDB8kF',
  description: 'Port Angeles; Mount Storm King' },
{ img_id: '1X1Z2UCcJ2vl5QAV3neHXG6xP3nkey7xD',
  description: 'Port Angeles; Mount Storm King' },
{ img_id: '1X6vieOP9eDCNZnfmL6NW97MwDGcJYVbW',
  description: 'Port Angeles; Mount Storm King' },
{ img_id: '1X7gELDXdWpfcz5MQceRKX0iLcgfMtu1L',
  description: 'Port Angeles; Olympic Hot Springs Road' },
{ img_id: '1XJw3ss2_JD4zvkr3X452aOfU9Tla9Pc5',
  description: 'Port Angeles; Salt Creek State Park Muscles' },
{ img_id: '1XGTjdVldV-8rhzzTjwfUrjlIzdmEqxdz',
  description: 'Port Angeles; Salt Creek State Park Tide Pool' },
{ img_id: '1XEgd5WrM0SEQgAlUhlhgJ1Saq1dH92bo',
  description: 'Port Angeles; Salt Creek State Park Tide Pool' },
{ img_id: '1XKVK9DuBzgIc7XTxZmBm85B0o78rdc_h',
  description: 'Port Angeles; Salt Creek State Park Tide Pool' },
{ img_id: '1XKfWUBac1lpo5KVUL8T1YDC-S3DTp0Pp',
  description: 'Port Angeles; Salt Creek State Park Blue Crab' },
{ img_id: '1XewOOmAlRMIfmnb9Cf-rtOgdvVABkHO6',
  description: 'Port Angeles; Salt Creek State Park' },
{ img_id: '1Xm_4JlGEeW737zav5JK_N7riN91KtEf4',
  description: 'Random; Peacock' },
{ img_id: '1XnfAJaf4LHGE_LuxxroeLLW3J0j5sWsV',
  description: 'Port Angeles; Mount Storm King' },
{ img_id: '1Xo8vNsUq71aO5jl8tR5xAqL2H-OedCLB',
  description: 'Random; Mount Rainier' },
{ img_id: '1S1ClaQgrYTBS7gbR8hRjJTCbW4Ov9ffr',
  description: 'Random; Forks Welcome Sign' },
{ img_id: '1Sem0NsohHP8kg351VyK_1m_jtcErULTW',
  description: 'Random; Kangaroo' },
{ img_id: '1Sb0tt_7wZpdZbKxyttByfPzFxCUgCW3o',
  description: 'Cape Flattery; Big Ole Chair' },
{ img_id: '1SayvOhBaYwV4kl-M39oRWzonXgMP06Xo',
  description: 'Random; Big Ole Tree' },
{ img_id: '1Sa71dXEocyPmRVlh8V7Ki-0R5UILtaJP',
  description: 'Seattle; Cityscape' },
{ img_id: '1SZ3wTGzpZ4NiQpxhKzulCg42HbBE8hZH',
  description: 'Random; Hoh Rainforest' },
{ img_id: '1SSOSXoHt9tDZGtLWThvGpTAa4j2RIVNx',
  description: 'Cape Flattery; Ocean Time' },
{ img_id: '1Y963OHohS7MJm4Hu9I0VUq9CZ2BE3hfV',
  description: 'Seattle; Cityscape' },
{ img_id: '1XtglHtXLQSNoGTYcdrUi-BMN5lbQ961n',
  description: 'Seattle; Ferry to Bainbridge' },
{ img_id: '1YGYddWRMyv2FfWMLx96J9I_DbN9fqD9W',
  description: 'Cape Flattery; Ocean Time' },
{ img_id: '1Sfu9uaUCSpEdI7adNtAGToEbxkERAjW9',
  description: 'Random; Zipline' } ]