import { ImageType } from "../../types/image-type"

export const pictures: ImageType[] = [
  { img_id: '11yRnkBm3YoyXBlb1XRG9lto22GLidMgh',
    description: 'Sydney; Royal National Park' },
  { img_id: '11w-N-fPjV3ImC_pIECjaZCMqiReNygXA',
    description: 'Sydney; Royal National Park' },
  { img_id: '11vDG-wtFaJ25BkEfPjDOlFUsX_QXGG8k',
    description: 'Sydney; Royal National Park' },
  { img_id: '1c8fqX3bYAGjByXjarAnOxgqdD7gJRSNM',
    description: 'Sydney; Bag Worm' },
  { img_id: '1cAtyQXk9qeW3MkG49TCQ0u_GZ0Qgd622',
    description: 'Sydney; Bag Worm' },
  { img_id: '1cDPTB8RqNVuDPYAOkmCYIjtv_ZWQs8JN',
    description: 'Sydney; Opera House and Harbor Bridge' },
  { img_id: '1cGJUTq8T4_7lf-CiSxJpxf-GHJwdja8a',
    description: 'Sydney; Sick Tree' },
  { img_id: '1cHEYMFGJzLbkc19ku_ms3sNZt3iRbRpx',
    description: 'Sydney; Butterfly' },
  { img_id: '1cW96IeaZhgvtoaD-0JQ6jYg4OcEjWSw_',
    description: 'Sydney; Butterfly - Twinkies' },
  { img_id: '1cXt6BbFXo-OjHDBt8pVwrkvb_iYOObM7',
    description: 'Sydney; The Grounds of Alexandria' },
  { img_id: '1caWkDJrPB07FZ5Df5O5QDeW9CafXFJnb',
    description: 'Sydney; Park' },
  { img_id: '1chBjmYGbcl55sLpbO5FCwGBxzsmdlhfD',
    description: 'Sydney; Cityscape' },
  { img_id: '1crt_QJWhD9CszumDI1k3vgfaSjDBIujq',
    description: 'Sydney; Ramadan Nights' },
  { img_id: '1cvuQTveCnWcp7qW9JEOzcZHncrLaI7ra',
    description: 'Sydney; St Mary\'s Cathedral' },
  { img_id: '1cxy9MLUVNqmQlRIfyxzaCmh58CL4_kRc',
    description: 'Sydney; St Mary\'s Cathedral' },
  { img_id: '1d3ob6z4oN6-guKrCDBsOWkYVuR0pZlsJ',
    description: 'Sydney; Australian Navy' },
  { img_id: '1dIKLRKxK_UooNMRB6LydbrvKpOlqNLdW',
    description: 'Sydney; Cityscape - The Crown' },
  { img_id: '1eE_DVi2vamQ8uRfvjRytskUI6RxR5g0y',
    description: 'Sydney; Royal National Park - Jacky Dragon' },
  { img_id: '1dIyr6yEYYv6CK7IjrgBvxw-sy7aDf-jV',
    description: 'Sydney; Disgusting Spider - Trichonephila Edulis' },
  { img_id: '1dKxsBbn5KHlr9cXWei79zR16WOB55Hco',
    description: 'Sydney; Royal National Park' },
  { img_id: '1dVow0qTkB5RU5JyNEMEdFu0ZwQlE78TY',
    description: 'Sydney; Bird: Rainbow Lorikeet' },
  { img_id: '1dWsAGRokBt2tOhg61zCNHO_nuWcE5lRf',
    description: 'Sydney; Royal National Park - Red Bull Ant' },
  { img_id: '1dXHVVGQPWTmAGNmi_ab6ag4gdCzf9G3m',
    description: 'Sydney; Royal National Park' },
  { img_id: '1d_vZJ0Blnps_BS628w1PyuCrVqrj8QJC',
    description: 'Sydney; Royal National Park' },
  { img_id: '1dgb8Pklh-VHbqjPPUSH6_151GxG_kbL1',
    description: 'Sydney; Royal National Park' },
  { img_id: '1dkxVzdcKw-LKVxV1zBnqA37Tj3QNXZR3',
    description: 'Sydney; Royal National Park' },
  { img_id: '1dmRBQnkvKaadWsDBiFmklSVCx811vwZP',
    description: 'Sydney; Royal National Park' },
  { img_id: '1dmjgMNZEKeJOfiZkx4Dx7MqkkIFZtJ8Z',
    description: 'Sydney; Royal National Park' },
  { img_id: '1e4_SUrQTI-ldkplNvmsaqH6KYR6xLIo7',
    description: 'Sydney; Royal National Park' },
  { img_id: '1eOuHMUd1xsJ8aMVztrsEEXhKoceoO_Ue',
    description: 'Sydney; Royal National Park' },
  { img_id: '1eP5m8Mm0fLF9nFDLwYcUd54CqS9GuJ6-',
    description: 'Sydney; Bird: Cockatoo' },
  { img_id: '1eVL0oWiRJXTS0_VMo0wxmz1_xqExF710',
    description: 'Sydney; Bird: Galah' },
  { img_id: '1eUOWRmRlXpcr3N_eR5Tn6YVTZ0GWYFE0',
    description: 'Sydney; Bird: Rainbow Lorikeet' },
  { img_id: '1aG2EXpIGQmjxZ0uMuz-lOxQo9t0OmKgo',
    description: 'Sydney; Crocheting by Opera House' },
  { img_id: '1a91COlYxaCk7sdJY3wiDdqy1MZVffLZL',
    description: 'Sydney; Crocheting by Opera House' },
  { img_id: '1a6mYHhBK5vHRWR75tGA7mqslCqmC4U8z',
    description: 'Sydney; Crocheting by Opera House' },
  { img_id: '1C5hfufb4l6Tsw2OcMfoEC2ZpEW2mPzKp',
    description: 'Sydney; Opera House' },
  { img_id: '1C0aMhJWOR8hJbL6WjVQb9skS8x2f_RNm',
    description: 'Sydney; Coogee Island' },
  { img_id: '1C1IzAuvRee1b9pa8yw-KtBdpIXmLa7Dl',
    description: 'Sydney; Coogee Island' },
  { img_id: '1BxhByWq1-b8MhDCOpbnsTQ0JPNFVP1AI',
    description: 'Sydney; Snorkeling' },
  { img_id: '1BxViNQSWyhsAWfXReSTJCsas7IFzATs8',
    description: 'Sydney; Snorkeling' },
  { img_id: '1Bp-Y5uFHU4alJ3AcEqrIPPOZBbKVhROJ',
    description: 'Sydney; Snorkeling' },
  { img_id: '1Bn3dqN25enVxb6MEiUQ0vYONQqslyAtx',
    description: 'Sydney; Snorkeling' },
  { img_id: '1Be97H0qy5Y6X-NCm71yLr4OXu9f4o0AY',
    description: 'Sydney; Snorkeling' },
  { img_id: '1BapLMdD8EbTB9dNap7XUxZe60_tWL8Vs',
    description: 'Sydney; Coogee Island' },
  { img_id: '1BWELOt0KN29qKjgtsROx-VfU-bdXz6Zf',
    description: 'Sydney; Cityscape' },
  { img_id: '1BCbr0qJmgwkaB7RCGShoFp7D9sVqvmYB',
    description: 'Sydney; Cityscape' },
  { img_id: '1BM6mhqExfBxcIgBKOS-mMFM6dCkXAn9i',
    description: 'Sydney; Bondi Beach' },
  { img_id: '1AzrEJ55Q20cAIQOyJ_Xd6LEGVyLIULnY',
    description: 'Sydney; Bondi Beach' },
  { img_id: '1AxolkGZoC7BljeMf37ix1Kn-g7muyy1Y',
    description: 'Sydney; Bondi Beach' },
  { img_id: '1AtNd3b_gjD1ilB_HNjcG8kJDIvZqcn1N',
    description: 'Sydney; Bondi Beach' },
  { img_id: '1AnadXqDLG2vTDM9wNQAbOaTaRtiuFJJU',
    description: 'Sydney; Coogee Island' },
  { img_id: '1AnQLuS6zhkO4E2QfxFtdY7IiPgHldATo',
    description: 'Sydney; Coogee Island' },
  { img_id: '1AmUg_L9GgAX4nrWlB9qSicFrVvoVhtaI',
    description: 'Sydney; Coogee Island' },
  { img_id: '1AnHpokLW5YVo4h11Nuv3n4J7A3Fn8hkZ',
    description: 'Sydney; Coogee Island' },
  { img_id: '1AhlOxMROOR25attCPGrAMh_HFcifkoov',
    description: 'Sydney; Coogee Island' },
  { img_id: '1AUD6LYWjT3HTB2HzhMAr09np0DAiEnS-',
    description: 'Sydney; Coogee Island' },
  { img_id: '1AhAxI90m4x1KhW5pl1buK_4_8b4mFGH6',
    description: 'Sydney; Coogee Island' },
  { img_id: '1ANs1yfLbkRMt-tsDY2lWXVFDdwopLi9W',
    description: 'Sydney; Coogee Island' },
  { img_id: '1ALYd1JQwRYq8OyPecenO1wgD4YiVarg6',
    description: 'Sydney; Coogee Island' },
  { img_id: '1ATGHbRq4EC8lQx8UF4Qo_FjKs8utlzGG',
    description: 'Sydney; Coogee Island' },
  { img_id: '1ALUcwEr0mjNQ5HjqlnH0WUKylc0v74KS',
    description: 'Sydney; Coogee Island' },
  { img_id: '1AKDiMbxbt4N0TWHmi8tQZgKRP7vlSmcP',
    description: 'Sydney; Coogee Island' },
  { img_id: '1AJsa6YY1ROQI3bCjlbJwImX9PSrxfDfc',
    description: 'Sydney; Coogee Island' },
  { img_id: '1AAeAQQ621zVF0ovomunJBmSE38zXfGs3',
    description: 'Sydney; Coogee Island' },
  { img_id: '1A6n3SZkQp2fxLnvcD0b9WraFDvr2NR6P',
    description: 'Sydney; Coogee Island' },
  { img_id: '1A5EivjIk6PVJG_eSYW7AT7ZQ6P27yXIu',
    description: 'Sydney; Coogee Island' },
  { img_id: '1A50Z3El_K4nKs0G5fcWh_FuIj6iMCKiR',
    description: 'Sydney; Coogee Island' },
  { img_id: '19pn4k_--6abNvgsCH6yPfX_cQf0ix52c',
    description: 'Sydney; Coogee Island' },
  { img_id: '19nbdqbF9oHdHXcysXrEWAH0BGwkoECb7',
    description: 'Sydney; Coogee Island' },
  { img_id: '19nPgoo7IKobBYxlVQTWhgyoAd2a-GJqJ',
    description: 'Sydney; Bird: Tiny lil guy' },
  { img_id: '19n1Fg5k6kZ6pTf31npuyHXo8RJF5zn8c',
    description: 'Sydney; Coogee Island' },
  { img_id: '19mNUOva658lHh5dN8VHodz7zav9l2aNJ',
    description: 'Sydney; Bird: Seagull' },
  { img_id: '19kYp-PZIv5P41T5_l8tdEiL9r5C1ibLw',
    description: 'Sydney; Coogee Island' },
  { img_id: '19c7c4zfZlD9Ctz0P8TVYSHy75oCNQqy-',
    description: 'Sydney; Cityscape- Aussie Big Ben' },
  { img_id: '19UJjDCCIWB2ucwv3fVphoUxqTf0E6Jkl',
    description: 'Sydney; Cityscape' },
  { img_id: '19Lu3IloCqLsByUxJirueeklrvVuqDOPT',
    description: 'Sydney; Opera House' },
  { img_id: '19WF0mCkARGT8obcbiGXRWn6yi18cisvM',
    description: 'Sydney; cityscape' },
  { img_id: '19IN4yN1pQ3u2d7wGLQhXjqO6S-3PJLt-',
    description: 'Sydney; Luna Park' },
  { img_id: '19_A1xEi6ZdrRwb9Y-jZRd6FWgtjBlDNp',
    description: 'Sydney; Harbor Bridge' },
  { img_id: '19admfXvtzBtl3h4RQjXJZB3uWFXomUlj',
    description: 'Sydney; Harbor Bridge' },
  { img_id: '19LeVT7qSIe8s58b_D_skd1RgOsJ-d4je',
    description: 'Sydney; Harbor Bridge' },
  { img_id: '19GK1PL_X5m3ero3C3CHg_-TbZYhNVBG3',
    description: 'Sydney; Harbor Bridge' },
    { img_id: '14byvzPpbDkBtawVYKnKp6cfsmWUmtFnf',
    description: 'Sydney; Slug' },
  { img_id: '1T-07ilCSKIz6lpB4eDn0BJsASGM2A6AI',
    description: 'Sydney; Disgusting Spider - Trichonephila Edulis' },
  { img_id: '1jPVJeUlNfbqSXws-sVTEZJxHIVq7D1iv',
    description: 'Sydney; Ramadan Nights - Potato on a Stick' },
  { img_id: '1uBfZw2-AD5Ir6JqsUUtquM0bzhpCzRJ0',
    description: 'Sydney; Sydney Olympic Park - Mangrove Forest' },
  { img_id: '12QsrpQ_SaLBsYr47cJXIfqMzafeKd0Fu',
    description: 'Sydney; Sydney Olympic Park' },
  { img_id: '17qp_iFPF6SwnGH-cxpQVbx_6MYzAi_L7',
    description: 'Sydney; Sydney Olympic Park - Mangrove Forest' },
  { img_id: '1LLiQz8hnzhZL7vlNL-8coWdE4EtJmoKb',
    description: 'Sydney; Sydney Olympic Park' },
  { img_id: '1QUChxh3opcy-bOBT2kYq_zW47Xxnzw0p',
    description: 'Sydney; Sydney Olympic Park - Golden Orb-Weaving Spider' },
  { img_id: '1SJnwi01vEcu7tVwLMCyl0NtV4o7tOGkv',
    description: 'Sydney; Sydney Olympic Park - Golden Orb-Weaving Spider' },
  { img_id: '1UAGoliKiUqWuwriR9uiHumdz5ygvlubS',
    description: 'Sydney; Sydney Olympic Park - Bar-Sided Skink' },
  { img_id: '1ggYmpr2Dy-ERcbXY_yeLYyixW2fnqo9U',
    description: 'Sydney; Sydney Olympic Park - Mangrove Forest' },
  { img_id: '1qvncoez9VKPl9abGNjzj2TPs-KHKOAZ-',
    description: 'Sydney; Sydney Olympic Park - Estuarine Crabs' },
  { img_id: '11uIL5m94g-DO1eWSZdRiAml3A0jLghT7',
    description: 'Sydney Zoo; Meerkats' },
  { img_id: '10lVMhsCFyfSnAyjykUVZV5p4in4qk1fd',
    description: 'Sydney; University of Sydney' },
  { img_id: '10kAFAjFwRp7R_b09lukh6A-KdNI4uld8',
    description: 'Sydney; University of Sydney' },
  { img_id: '10_mLT4gQCM5JFhq2Kl8PTj7jnUQGwIE-',
    description: 'Sydney; University of Sydney' },
  { img_id: '10j-s-_S4wFfqPBrV4CF3YGt-CpeWjIxZ',
    description: 'Sydney; University of Sydney' },
  { img_id: '10h3JQH_TrurZI2CKSEt8qmS7TfmtFEMC',
    description: 'Sydney; University of Sydney' },
  { img_id: '10aB3bG3ZoWJnj6oUMQvtD_9wpUlCvqOc',
    description: 'Sydney; University of Sydney' },
  { img_id: '10m5VUF4AoekiNCfOk0EaquCiys8xPfFi',
    description: 'Sydney; University of Sydney' },
  { img_id: '1--50D_9XJ6Grszx7ONUe02Oiud7ieSvN',
    description: 'Sydney; Bird: Raven' },
  { img_id: '1-fwtrmLd-UbsE6F17PYSsnOkoTKCO4f9',
    description: 'Sydney; Cityscape' },
  { img_id: '1BMgAppb-oPhGXsW4L1qkaDCbgCQ_ocNl',
    description: 'Sydney; Cityscape' },
  { img_id: '1V2KN1dWV6daARpV9YKycsHsM2Z8yObzO',
    description: 'Sydney; Kylee in Spoon' },
  { img_id: '1huH1Va-KqKJ6SS3y0Edp7ZZcQ6354Ukn',
    description: 'Sydney; Cityscape' },
  { img_id: '1lvJQDnNWBFPL1Il3WRhCfWraDUKfLD2i',
    description: 'Sydney; Cityscape' },
  { img_id: '1m5vGGncAy2kGJTYKWM3yj-ARSgMUTaeb',
    description: 'Sydney; Bird: Twig Legs' },
  { img_id: '1o_tepPU9w0lFWR2RyJYbUuchDLikmdvD',
    description: 'Sydney; Bird: Blue Yellow Legs' },
  { img_id: '1xJGErqFqKKBhMwYZIv8BoSVcXd2OEmZL',
    description: 'Sydney; Bird: Turkey' },
  { img_id: '14dgeTTWootVVGq3G0fTaYvOKwnw9Z0pq',
    description: 'Sydney; Cityscape at night' },
  { img_id: '1G9mBPB1UkjG7U2pKYLs3Znc-3ZzHoXHt',
    description: 'Sydney; Cityscape' },
  { img_id: '1MoOFGUtza3GDvStd8449wRiv-HHS4zjY',
    description: 'Sydney; Bird: Cockatoo' },
  { img_id: '1NbWvp2ZmjMKA9itdguhDxalbQ0NY9lqi',
    description: 'Sydney; Bird: Magpie' },
  { img_id: '1RN2E_8rsu1Q39e-zoyQ1s0I4jLRrmZ_U',
    description: 'Sydney; China Town' },
  { img_id: '1WeOX9LP_6CmX_HFcewsoI2ZVQXuvp3V2',
    description: 'Sydney; Bird: Silly guy with built-in hat' },
  { img_id: '1YR_hrfNFmvJZG1hCNthRQfiDZPgx-Lzm',
    description: 'Sydney; Bird: Bin Chicken' },
  { img_id: '1Ymd1woiGujjcB4XL-6kdZT6iA7nJ_r5I',
    description: 'Sydney; Cityscape' },
  { img_id: '1fZ2pJEhHY8NnuGXP5yRNQ8ZBDMPIt7_0',
    description: 'Sydney; Cityscape' },
  { img_id: '1u44TG9qkzeYc86n6TaC6FGNMGcp0c2b6',
    description: 'Sydney; Cityscape- Aussie Big Ben' }, 
  { img_id: '1gewlT3_4YkfiaHPOxaE_-YOeRxVnvNsD',
    description: 'Taronga Zoo; Entrance' },
  { img_id: '199gnwYPpcDS2Fp0HfzHDCWkpZztB7u9U',
    description: 'Taronga Zoo; Kangaroos' },
  { img_id: '1OjysPDcEkXxnGY3bsaPIEbOtllysKHfk',
    description: 'Taronga Zoo; Koala' },
  { img_id: '1an-aY46sNMpFKhra5LzpnGlNe-cCIC1s',
    description: 'Taronga Zoo; Dingo (Dog but in Zoo)' },
  { img_id: '1oxpNIRINjSDKYLC9kCOqU38lXSbVWETg',
    description: 'Taronga Zoo; Bats' },
  { img_id: '1tSJ6VN4bprFqlnWBjG1lQ7TjO_m0Ax-g',
    description: 'Taronga Zoo; Wallaby' },
  { img_id: '1wmCQnprTEMSvscRIMmU_eqtqTaBCEjvk',
    description: 'Taronga Zoo; Eastern Water Dragon' },
  { img_id: '1z2jaUZLnXj5CPt4Oi3VUescpJuj59Qz5',
    description: 'Taronga Zoo; Kangaroo' },
  { img_id: '19sq_0rthPsSIsHkP-aOeXT-wHjzuQ29e',
    description: 'Taronga Zoo; Koala' },
  { img_id: '1FLxPPwZAY3v-1d7nMpMsOBqq7okHX9G7',
    description: 'Taronga Zoo; Seal' },
  { img_id: '1lQ4TCO2igJnAOOhIs81XX4bn0fixvuOa',
    description: 'Taronga Zoo; Seal Pup' },
  { img_id: '1EshSEQGtLS2iHmCywer0BheVLwb9zYf2',
    description: 'Taronga Zoo; Capybara' },
  { img_id: '1MoKwvuGO_bREBap3tX-iB0kIZuZaU8hr',
    description: 'Taronga Zoo; Quokka' },
  { img_id: '1TutynOaC3-iXjvy2R-9h14j-f00MqKjS',
    description: 'Taronga Zoo; Giraffe' },
  { img_id: '1Wdyii1xhgmONTYY4hlKWqTVfbH777ezT',
    description: 'Taronga Zoo; Baby Hippo' },
  { img_id: '1Yq9ZnTq0V7NqCFRjwqvX4i8c-5940NMa',
    description: 'Taronga Zoo; Gorilla' },
  { img_id: '1_aRdIjwpqHm0nrNlFW_-pfDZMG3D8B0h',
    description: 'Taronga Zoo; Meerkats' },
  { img_id: '1pM5hghMlm0-SrziWBCrliMPeI882OAC5',
    description: 'Taronga Zoo; Meerkat' },
  { img_id: '1raVDHsNFolSPrDag-6v6b8JTfzzqdX1g',
    description: 'Taronga Zoo; Hippo' },
  { img_id: '1xo6h1g_FSibLR2kknowWpQcFxWXeS7Tc',
    description: 'Taronga Zoo; Baby Hippo' },
  { img_id: '1aJOW2QMwQ95X1O53Y7T0hzf4Wm0dYs8W',
    description: 'Taronga Zoo; Cityscape' }
]