import { ImageType } from "../../types/image-type"

export const pictures: ImageType[] = [
  { img_id: '1C5hfufb4l6Tsw2OcMfoEC2ZpEW2mPzKp',
  description: 'Sydney; Opera House' },
{ img_id: '1C0aMhJWOR8hJbL6WjVQb9skS8x2f_RNm',
  description: 'Sydney; Coogee Island' },
{ img_id: '1C1IzAuvRee1b9pa8yw-KtBdpIXmLa7Dl',
  description: 'Sydney; Coogee Island' },
{ img_id: '1BxhByWq1-b8MhDCOpbnsTQ0JPNFVP1AI',
  description: 'Sydney; Snorkeling' },
{ img_id: '1BxViNQSWyhsAWfXReSTJCsas7IFzATs8',
  description: 'Sydney; Snorkeling' },
{ img_id: '1Bp-Y5uFHU4alJ3AcEqrIPPOZBbKVhROJ',
  description: 'Sydney; Snorkeling' },
{ img_id: '1Bn3dqN25enVxb6MEiUQ0vYONQqslyAtx',
  description: 'Sydney; Snorkeling' },
{ img_id: '1Be97H0qy5Y6X-NCm71yLr4OXu9f4o0AY',
  description: 'Sydney; Snorkeling' },
{ img_id: '1BapLMdD8EbTB9dNap7XUxZe60_tWL8Vs',
  description: 'Sydney; Coogee Island' },
{ img_id: '1BWELOt0KN29qKjgtsROx-VfU-bdXz6Zf',
  description: 'Sydney; Cityscape' },
{ img_id: '1BCbr0qJmgwkaB7RCGShoFp7D9sVqvmYB',
  description: 'Sydney; Cityscape' },
{ img_id: '1BM6mhqExfBxcIgBKOS-mMFM6dCkXAn9i',
  description: 'Sydney; Bondi Beach' },
{ img_id: '1AzrEJ55Q20cAIQOyJ_Xd6LEGVyLIULnY',
  description: 'Sydney; Bondi Beach' },
{ img_id: '1AxolkGZoC7BljeMf37ix1Kn-g7muyy1Y',
  description: 'Sydney; Bondi Beach' },
{ img_id: '1AtNd3b_gjD1ilB_HNjcG8kJDIvZqcn1N',
  description: 'Sydney; Bondi Beach' },
{ img_id: '1AnadXqDLG2vTDM9wNQAbOaTaRtiuFJJU',
  description: 'Sydney; Coogee Island' },
{ img_id: '1AnQLuS6zhkO4E2QfxFtdY7IiPgHldATo',
  description: 'Sydney; Coogee Island' },
{ img_id: '1AmUg_L9GgAX4nrWlB9qSicFrVvoVhtaI',
  description: 'Sydney; Coogee Island' },
{ img_id: '1AnHpokLW5YVo4h11Nuv3n4J7A3Fn8hkZ',
  description: 'Sydney; Coogee Island' },
{ img_id: '1AhlOxMROOR25attCPGrAMh_HFcifkoov',
  description: 'Sydney; Coogee Island' },
{ img_id: '1AUD6LYWjT3HTB2HzhMAr09np0DAiEnS-',
  description: 'Sydney; Coogee Island' },
{ img_id: '1AhAxI90m4x1KhW5pl1buK_4_8b4mFGH6',
  description: 'Sydney; Coogee Island' },
{ img_id: '1ANs1yfLbkRMt-tsDY2lWXVFDdwopLi9W',
  description: 'Sydney; Coogee Island' },
{ img_id: '1ALYd1JQwRYq8OyPecenO1wgD4YiVarg6',
  description: 'Sydney; Coogee Island' },
{ img_id: '1ATGHbRq4EC8lQx8UF4Qo_FjKs8utlzGG',
  description: 'Sydney; Coogee Island' },
{ img_id: '1ALUcwEr0mjNQ5HjqlnH0WUKylc0v74KS',
  description: 'Sydney; Coogee Island' },
{ img_id: '1AKDiMbxbt4N0TWHmi8tQZgKRP7vlSmcP',
  description: 'Sydney; Coogee Island' },
{ img_id: '1AJsa6YY1ROQI3bCjlbJwImX9PSrxfDfc',
  description: 'Sydney; Coogee Island' },
{ img_id: '1AAeAQQ621zVF0ovomunJBmSE38zXfGs3',
  description: 'Sydney; Coogee Island' },
{ img_id: '1A6n3SZkQp2fxLnvcD0b9WraFDvr2NR6P',
  description: 'Sydney; Coogee Island' },
{ img_id: '1A5EivjIk6PVJG_eSYW7AT7ZQ6P27yXIu',
  description: 'Sydney; Coogee Island' },
{ img_id: '1A50Z3El_K4nKs0G5fcWh_FuIj6iMCKiR',
  description: 'Sydney; Coogee Island' },
{ img_id: '19pn4k_--6abNvgsCH6yPfX_cQf0ix52c',
  description: 'Sydney; Coogee Island' },
{ img_id: '19nbdqbF9oHdHXcysXrEWAH0BGwkoECb7',
  description: 'Sydney; Coogee Island' },
{ img_id: '19nPgoo7IKobBYxlVQTWhgyoAd2a-GJqJ',
  description: 'Sydney; Bird: Tiny lil guy' },
{ img_id: '19n1Fg5k6kZ6pTf31npuyHXo8RJF5zn8c',
  description: 'Sydney; Coogee Island' },
{ img_id: '19mNUOva658lHh5dN8VHodz7zav9l2aNJ',
  description: 'Sydney; Bird: Seagull' },
{ img_id: '19kYp-PZIv5P41T5_l8tdEiL9r5C1ibLw',
  description: 'Sydney; Coogee Island' },
{ img_id: '19c7c4zfZlD9Ctz0P8TVYSHy75oCNQqy-',
  description: 'Sydney; Cityscape- Aussie Big Ben' },
{ img_id: '19UJjDCCIWB2ucwv3fVphoUxqTf0E6Jkl',
  description: 'Sydney; Cityscape' },
{ img_id: '19Lu3IloCqLsByUxJirueeklrvVuqDOPT',
  description: 'Sydney; Opera House' },
{ img_id: '19WF0mCkARGT8obcbiGXRWn6yi18cisvM',
  description: 'Sydney; cityscape' },
{ img_id: '19IN4yN1pQ3u2d7wGLQhXjqO6S-3PJLt-',
  description: 'Sydney; Luna Park' },
{ img_id: '19_A1xEi6ZdrRwb9Y-jZRd6FWgtjBlDNp',
  description: 'Sydney; Harbor Bridge' },
{ img_id: '19admfXvtzBtl3h4RQjXJZB3uWFXomUlj',
  description: 'Sydney; Harbor Bridge' },
{ img_id: '19LeVT7qSIe8s58b_D_skd1RgOsJ-d4je',
  description: 'Sydney; Harbor Bridge' },
{ img_id: '19GK1PL_X5m3ero3C3CHg_-TbZYhNVBG3',
  description: 'Sydney; Harbor Bridge' },
{ img_id: '19C2GRGx2a8dz6u3_9TQpIUYiXumbAteQ',
  description: 'Sydney; Cityscape' },
{ img_id: '192R8-VwRcOBeKsyBsu4dgLFmFM-oXAFA',
  description: 'Sydney; Cityscape' },
{ img_id: '19-sCYSGS7M-kIp1L_BxGxyawCqM7A0if',
  description: 'Sydney; Bird: Blue Yellow Legs' },
{ img_id: '18wtTq6dYaAOuD12jhJ0QncC8H91spym6',
  description: 'Sydney; Bird: Twig Legs' },
{ img_id: '18t-mJw8xuMhhwMpxWMml0UYDVn2zRfRI',
  description: 'Sydney; Bird: Turkey' },
{ img_id: '18puk650BvZss1lqUYF_Y8maxODHojN9e',
  description: 'Sydney; Olympic Park Trees' },
{ img_id: '18j6gegl7h6N3LSvsgZ7s-JLrWnOkEHVl',
  description: 'Sydney; Kylee in Spoon' },
{ img_id: '17B5phEPVNq8YI5N3Mw9GFVKqhggrsawQ',
  description: 'Sydney; Cityscape- Aussie Big Ben' },
{ img_id: '17_Mk3KJxm30fknHiZWGJirPMi00VhRUo',
  description: 'Sydney; Bird: Magpie' },
{ img_id: '17ho_irQfwHjAWq_zQfwb3a8zJuJfOQuQ',
  description: 'Sydney; Bird: Cockatoo' },
{ img_id: '17U5vAbr2AplxJGDsk1787XnDhEfopUYQ',
  description: 'Sydney; Bird: Silly guy with built-in hat' },
{ img_id: '17XhWZ-YYLHQCEa6cmSGuDGJRiV784Qr8',
  description: 'Sydney; Bird: Bin Chicken' },
{ img_id: '16oQZGjAoVjNVOgm0OY2X_lq0WC_alGqB',
  description: 'Sydney; Bird: Raven' },
{ img_id: '16rqeLgGWkNJHClX5gOHZKyrjiZYc1Jfu',
  description: 'Sydney; Cityscape' },
{ img_id: '16okrBt9e5m6P8tp8RZPdQmIG8Q4Jea4u',
  description: 'Sydney; Cityscape' },
{ img_id: '171oO9MM4kXAFFYoloXARD62bF2JHpw54',
  description: 'Sydney; China Town' },
{ img_id: '1720oWdPX16oNNCpE9A4CoHrxWX6N4cN5',
  description: 'Sydney; Cityscape' },
{ img_id: '17ERgqeKHNW2bgoSa-mWGJMbFkRgbxQCA',
  description: 'Sydney; Cityscape' },
{ img_id: '17PzYU9DjyS_-xpOkOMbBsNucJxTGSrff',
  description: 'Sydney; Cityscape at night' },
{ img_id: '17KUId4dbGt9ruLd8QFJo3DoZLXSt9d-W',
  description: 'Sydney; Cityscape' }
]